### ISSUE TITLE
a small optimization

### ISSUE THREAD

**Issue by bpycinski** [Miko008/SDAonCUDA#2]
https://github.com/Miko008/SDAonCUDA/blob/457e5c998406faca512d2353917d3a6cc61fad22/SDAonCUDA/test.cu#L54

The line above is equivalent to:

`if (condtition_1 && condtition_2 && condtition_3)`

Here, `condition_1` is the most CPU-consuming. On the other hand, it evaluates to False in approx. 20%, while `condition_2` and `condition_3` evaluate to True much more often.

Anyway, I think that the it would be better to move condition_3 to the last position.

**Comment by Miko008** [comment]
Also moved multiply operation to caller in argument passing.
