### ISSUE TITLE
casting error

### ISSUE THREAD

**Issue by bpycinski** [Miko008/SDAonCUDA#3]
https://github.com/Miko008/SDAonCUDA/blob/457e5c998406faca512d2353917d3a6cc61fad22/SDAonCUDA/test.cu#L74

Something is wrong here. Casting is a higher-ranked operand than adding, see [the tables](https://en.cppreference.com/w/cpp/language/operator_precedence).

**Comment by Miko008** [comment]
Decided on cmath ceil function
